name = "Simple"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "very simply blog theme."
homepage = "https://github.com/lilonghe/hugo-theme-simply"
tags = [blog]
features = [private]
min_version = "0.41.0"

[author]
  name = "lilonghe"
  homepage = "https://github.com/lilonghe"